var GAME_LEVELS = [
  ["y  xy      xxxxx    xxxxx y ",
   "y x y          y        y y",
   "y   y      xxxxx    xxxxy y",
   "y   y      y            y y",
   "y xxxxx    xxxxx    xxxxx y",
   "y                         y",
   "y   a        b        c   y",
   "y  xxx      xxx      xxx  y",
   "y                         y",
   "y                         y",
   "y            @            y",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["y             v                                        v                     y",
   "y                         v                                                  y",
   "y     v                                       v                              y",
   "y                                                               v            y",
   "y                     v                                                      y",
   "y                                                                            y",
   "y          v                                                                 y",
   "y                                                xx                          y",
   "y                                 o o      xx                                y",
   "y                                                    yy!yy         o         y",
   "y                               xxxxx                yyxyy        xxx        y",
   "y                                                      v              xx     y",
   "y                              yy sss   sss     y o                          y",
   "y                    o  yy     yy  sss sss      y o                          y",
   "y                       yy     yy   sssss       xxxxx                     o  y",
   "y        y      y o     yy     yy    sss                 o                x  y",
   "y  @     y      y       yy     yy     s                                      y",
   "xxxxxy   y  y   y   y   yy     yyxxxxxxxxxx     yxxxxxxxxxxxxx     xxxxxxxxxxx",
   "     y   y  y   y   y   yy     yy         y     y            y     y          ",
   "     y!!!y!!y!!!y!!!y!!!yy!!!!!yy         y!!!!!y            yy   yy          ",
   "     y!!!y!!y!!!y!!!y!!!yy!!!!!yy         y!!!!!y            yyy!yyy          ",
   "     xxxxxxxxxxxxxxxxxxxxxxxxxxxx         xxxxxxx            xxxxxxx          ",
   "                                                                              ",
   "                                                                              "],
  ["y                                                                                    v      y",
   "y                                                                               v           y",
   "y                                                                                           y",
   "y                                                                                           y",
   "y                                                                                           y",
   "y                                                                                           y",
   "y                    v                                                                      y",
   "y                        v                                                                  y",
   "y                      v                                                                    y",
   "y                                                                                   o       y",
   "y                                                                                   x       y",
   "y                                                                                           y",
   "y                                                                                      o    y",
   "y                                            yxxxxxxxxxxy                    o    xx   x    y",
   "y                                          y ysss   sss y                   xx              y",
   "y                                        y y y sss sss                                      y",
   "y                                      y y y y  sssss                   xx                  y",
   "y                                    y y y y y   sss    y                   xx              y",
   "y       y  =     y                 y y y y y y    s     y                        xx         y",
   "y       y      = y               y y y y y y yxxxxxxxxxxy                                   y",
   "y    @  y    =   y             y y y y y y y y          y            y       yy             y",
   "xxxxxxxxxxxxxxxxxxxxy     yxxxxy y y y y y y y          y o          y  0    yy             y",
   "                    y     y    y y y y y y y y          y            y  =    yy             y",
   "                    y!!!!!y    y!y!y!y!y!y!y!y          yxxxxxxxxxxxxxxxxxxxxyy             y",
   "                    y!!!!!y    y!y!y!y!y!y!y!y                                y!!!!!!!!!!!!!y",
   "                    xxxxxxx    xxxxxxxxxxxxxxx                                xxxxxxxxxxxxxxx",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             "],
  ["                                                                                       y",
   "y                                                                                      y",
   "y                                                                                      y",
   "y    v      v          v        v                                                      y",
   "y                                                                                      y",
   "y                                                                                      y",
   "y                        o                                                             y",
   "y                        x                                                             y",
   "y                                                                                      y",
   "y                   xx       xx                                                        y",
   "y                                                                                      y",
   "y              xx                xx                                                    y",
   "y                                                                                      y",
   "y         xx            o           =xx                                                y",
   "y                       x                                                              y",
   "y    xx                                 =xx                     y                      y",
   "y                                                               y                      y",
   "yxx                                         =xx                 y                      y",
   "y                                                         =y    y   v                  y",
   "y  o  xx|          |         |      |     xx                   oy                      y",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         yy                      y",
   "y                                                    y    y     y                      y",
   "y                                                    yo                                y",
   "y                                                    yy              =xxx              y",
   "y                                                    y          y                      y",
   "y                                    o               yxxxxxxxxxxy         =xxx         y",
   "y                                  =xxx                                            o   y",
   "y                            o                                      =xxx          xxx  y",
   "y        o                 =xxx                               o                        y",
   "y      =xxx            o                                    =xxx              xxx      y",
   "y                    =xxx                      sss   sss         x          x          y",
   "y             o                                 sss sss                o               y",
   "y   o       =xxx                                 sssss               =xxx              y",
   "y  xxx                                            sss           o                      y",
   "y@                      =                          s          =xxx                     y",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxy yxy yxy yxy y",
   "                                                                         y!y y!y y!y y!y",
   "                                                                         xxx xxx xxx xxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
